# Generated by Django 6.0.6 on 2026-06-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_mediaitem_current_episode_mediaitem_current_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='total_episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='total_seasons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
