# Generated by Django 6.0.6 on 2026-06-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_mediaitem_total_episodes_mediaitem_total_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='seasons_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
