# Generated by Django 6.0.6 on 2026-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
